---
name: test
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=rootR00!' -p 1433:1433 -d --name sql1 --hostname sql1 mcr.microsoft.com/mssql/server:2022-latest
      - run: docker ps
      - run: docker logs sql1
      - run: nc -zv localhost 1433
      - run: sleep 20
      - run: docker ps
      - run: docker logs sql1
      - run: nc -zv localhost 1433
      - run: sqlcmd -S localhost -d master -U sa -P "rootR00!" -Q "sqlcmd -S ServerName -d DatabaseName -Q "SELECT * FROM INFORMATION_SCHEMA.TABLES"
      - run: docker build -t this .
      - run: docker run -e URL=localhost -e USERNAME=sa -e PASSWORD=root this
      - run: sqlcmd -S localhost -d master -U sa -P "rootR00!" -Q "sqlcmd -S ServerName -d DatabaseName -Q "SELECT * FROM INFORMATION_SCHEMA.TABLES"
